name: client_app
publish_to: "none"

version: 0.0.4+5

environment:
  sdk: ^3.1.0-0
  flutter: ^3.13.0-0

dependencies:
  action_slider: ^0.7.0
  adaptive_dialog: ^1.9.0
  animations: ^2.0.8
  clock: ^1.1.1
  cloud_firestore: ^4.9.0
  cloud_functions: ^4.4.0
  collection: ^1.18.0
  core:
    path: ../core
  device_info_plus: ^9.0.3
  firebase_analytics: ^10.4.5
  firebase_app_check: ^0.1.5+2
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_performance: ^0.9.2+5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^10.1.2
  google_maps_flutter:
    git:
      url: https://github.com/KoheiKanagu/packages
      ref: indoor
      path: packages/google_maps_flutter/google_maps_flutter
  google_mobile_ads: ^3.0.0
  hooks_riverpod: ^2.3.10
  intersperse: ^2.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  package_info_plus: ^4.1.0
  permission_handler: ^10.4.3
  riverpod_annotation: ^2.1.4
  share_plus: ^7.1.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  go_router_builder: ^2.3.1
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  pedantic_mono: ^1.24.0
  pigeon: ^11.0.0
  riverpod_generator: ^2.3.1
  riverpod_lint: ^2.0.3
  test: ^1.24.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf

flutter_native_splash:
  color: "#FAFDFD" # lightColorScheme.background
  image: "../../assets/splash_icon.png"
  color_dark: "#191C1D" # darkColorScheme.background
  image_dark: "../../assets/splash_icon_dark.png"
  android_12:
    image: "../../assets/splash_icon.png"
    color: "#FAFDFD" # lightColorScheme.background
    image_dark: "../../assets/splash_icon_dark.png"
    color_dark: "#191C1D" # darkColorScheme.background
  android: true
  ios: true
  fullscreen: true
