name: client_app
publish_to: "none"

version: 0.0.0+0

environment:
  sdk: ^3.1.0-0
  flutter: ^3.11.0-0

dependencies:
  clock: ^1.1.1
  cloud_firestore: ^4.7.1
  core:
    path: ../core
  device_preview: ^1.1.0
  firebase_analytics: ^10.4.1
  firebase_app_check: ^0.1.5
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_crashlytics: ^3.3.1
  firebase_performance: ^0.9.2+1

  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: any
  gap: ^3.0.0
  go_router: ^7.0.2
  hooks_riverpod: ^2.3.6
  intl: any
  json_annotation: ^4.8.1
  package_info_plus: ^4.0.1
  riverpod_annotation: ^2.1.1
  url_launcher: ^6.1.11
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.4
  custom_lint: ^0.4.0
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  go_router_builder: ^2.0.1
  json_serializable: ^6.7.0
  mockito: ^5.4.0
  pedantic_mono: ^1.22.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/
