name: client_app
publish_to: "none"

version: 0.0.0+0

environment:
  sdk: ^3.1.0-0
  flutter: ^3.11.0-0

dependencies:
  adaptive_dialog: ^1.9.0
  animations: ^2.0.7
  clock: ^1.1.1
  cloud_firestore: ^4.8.3
  core:
    path: ../core
  device_info_plus: ^9.0.2
  device_preview: ^1.1.0
  firebase_analytics: ^10.4.4
  firebase_app_check: ^0.1.5
  firebase_auth: ^4.7.1
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.4
  firebase_performance: ^0.9.2+3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: any
  gap: ^3.0.1
  go_router: ^10.0.0
  # google_maps_flutter: ^2.3.1
  google_maps_flutter:
    git:
      url: https://github.com/KoheiKanagu/packages
      ref: indoor
      path: packages/google_maps_flutter/google_maps_flutter
      # path: /Users/kingu/Develop/packages/packages/google_maps_flutter/google_maps_flutter # for develop
  google_mobile_ads: ^3.0.0
  hooks_riverpod: ^2.3.6
  intl: any
  json_annotation: ^4.8.1
  package_info_plus: ^4.0.2
  permission_handler: ^10.4.3
  riverpod_annotation: ^2.1.1
  url_launcher: ^6.1.12
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  go_router_builder: ^2.2.4
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  pedantic_mono: ^1.23.0
  pigeon: ^10.0.0
  riverpod_generator: ^2.2.4
  riverpod_lint: ^1.4.0
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/google_maps/
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
