version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Asia/Tokyo"

  - package-ecosystem: "pub"
    directory: "/packages/core"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Asia/Tokyo"
    groups:
      firebase:
        patterns:
          - "firebase_*"
          - "cloud_firestore"
          - "cloud_functions"
      freezed:
        patterns:
          - "freezed_annotation"
          - "freezed"
          - "json_annotation"
          - "json_serializable"
      riverpod:
        patterns:
          - "hooks_riverpod"
          - "riverpod_*"
      go_router:
        patterns:
          - "go_router"
          - "go_router_builder"

  - package-ecosystem: "pub"
    directory: "/packages/client_app"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Asia/Tokyo"
    groups:
      firebase:
        patterns:
          - "firebase_*"
          - "cloud_firestore"
          - "cloud_functions"
      freezed:
        patterns:
          - "freezed_annotation"
          - "freezed"
          - "json_annotation"
          - "json_serializable"
      riverpod:
        patterns:
          - "hooks_riverpod"
          - "riverpod_*"
      go_router:
        patterns:
          - "go_router"
          - "go_router_builder"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 100
