version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 100

  - package-ecosystem: "pub"
    directory: "/packages/core"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 100

  - package-ecosystem: "pub"
    directory: "/packages/client_app"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 100

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 100
