# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - "**/firebase_options*.dart"
    - "build/**"
    - "ios/**"
    - "android/**"
    - "firebase/**"
    - "python/**"
    - "assets/**"
    - "coverage/**"
    - ".dart_tool/**"
  plugins:
    - custom_lint
