targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          include:
            - lib/features/*/domain/**.dart
            - lib/features/*/application/**.dart
            - lib/routing/**.dart
            - lib/constants/**.dart
            - lib/models/**.dart
            - lib/providers/**/**.dart
      json_serializable:
        options:
          checked: true
          explicit_to_json: true
          include_if_null: true
      riverpod_generator:
        generate_for:
          exclude:
            - "test/mocks/*.dart"
