targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
        generate_for:
          include:
            - lib/features/*/domain/**.dart
            - lib/features/*/application/**.dart
            - lib/routing/**.dart
            - lib/constants/**.dart
            - lib/router/**.dart # delta_guild_370709
      json_serializable:
        options:
          checked: true
          explicit_to_json: true
          include_if_null: true
      riverpod_generator:
        generate_for:
          exclude:
            - "test/mocks/*.dart"
