name: core
version: 0.0.0+0

environment:
  sdk: ^3.1.0-0
  flutter: ^3.11.0-0

dependencies:
  cloud_firestore: ^4.7.1
  firebase_analytics: ^10.4.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_crashlytics: ^3.3.1
  firebase_dynamic_links: ^5.3.1
  firebase_performance: ^0.9.2+1
  flutter:
    sdk: flutter
  freezed_annotation: 2.2.0
  hooks_riverpod: ^2.3.6
  json_annotation: ^4.8.1
  package_info_plus: ^4.0.1
  riverpod_annotation: ^2.1.1
  roggle: ^0.3.2
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.4
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  mockito: ^5.4.0
  pedantic_mono: ^1.22.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  test: any

flutter: null
