name: core
publish_to: "none"

version: 0.0.0+0

environment:
  sdk: ^3.1.0-0
  flutter: ^3.13.0-0

dependencies:
  adaptive_dialog: ^1.9.0
  clock: ^1.1.1
  cloud_firestore: ^4.8.5
  cloud_functions: ^4.4.0
  collection: ^1.17.2
  device_info_plus: ^9.0.3
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_dynamic_links: ^5.3.5
  firebase_performance: ^0.9.2+5
  firebase_ui_auth: ^1.6.4
  firebase_ui_oauth_apple: ^1.2.8
  firebase_ui_oauth_google: ^1.2.8
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  geoflutterfire_plus: ^0.0.16
  go_router: ^10.1.0
  google_maps_flutter:
    git:
      url: https://github.com/KoheiKanagu/packages
      ref: indoor
      path: packages/google_maps_flutter/google_maps_flutter
  hooks_riverpod: ^2.3.10
  intersperse: ^2.0.0
  json_annotation: ^4.8.1
  package_info_plus: ^4.1.0
  riverpod_annotation: ^2.1.4
  roggle: ^0.3.2
  shared_preferences: ^2.2.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  go_router_builder: ^2.3.0
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  pedantic_mono: ^1.23.0
  riverpod_generator: ^2.3.1
  riverpod_lint: ^2.0.3
  test: ^1.24.3

flutter:
  assets:
    - assets/google_maps/
