name: core
publish_to: "none"

version: 0.0.0+0

environment:
  sdk: ^3.2.0-0
  flutter: ^3.16.0-0

dependencies:
  adaptive_dialog: ^1.9.0+2
  clock: ^1.1.1
  cloud_firestore: ^4.9.3
  cloud_functions: ^4.4.2
  collection: ^1.18.0
  device_info_plus: ^9.1.0
  firebase_analytics: ^10.5.1
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_crashlytics: ^3.3.7
  firebase_dynamic_links: ^5.3.7
  firebase_performance: ^0.9.3
  firebase_ui_auth: ^1.9.0
  firebase_ui_oauth_apple: ^1.2.12
  firebase_ui_oauth_google: ^1.2.12
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  geoflutterfire_plus: ^0.0.19
  go_router: ^11.1.4
  google_maps_flutter:
    git:
      url: https://github.com/KoheiKanagu/packages
      ref: c8dd2d786b2f056245a8da175c6ef59a84ec5391
      path: packages/google_maps_flutter/google_maps_flutter
  hooks_riverpod: ^2.4.4
  intersperse: ^2.0.0
  json_annotation: ^4.8.1
  package_info_plus: ^4.2.0
  riverpod_annotation: ^2.2.1
  roggle: ^0.4.2+1
  shared_preferences: ^2.2.2
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  go_router_builder: ^2.3.3
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  pedantic_mono: ^1.24.0+1
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  test: ^1.24.8

flutter:
  assets:
    - assets/google_maps/
