name: Setup Flutter
description: Setup Flutter SDK

inputs:
  use_local_dart:
    description: Use local Dart SDK
    required: true
    default: "false"

  flutter_branch:
    description: Flutter branch
    required: false
    default: "beta"

runs:
  using: "composite"
  steps:
    - name: Cache Flutter
      if: inputs.use_local_dart == 'false'
      uses: actions/cache@v3.3.1
      with:
        path: $HOME/fvm/versions
        key: flutter-v1

    - name: Clone Flutter
      if: inputs.use_local_dart == 'false'
      uses: actions/checkout@v3
      with:
        repository: flutter/flutter
        ref: ${{ inputs.flutter_branch }}
        path: $HOME/fvm/versions/${{ inputs.flutter_branch }}

    - name: PATH
      if: inputs.use_local_dart == 'false'
      shell: bash
      run: |
        echo "$HOME/fvm/versions/${{ inputs.flutter_branch }}/bin" >> $GITHUB_ENV
        echo "$HOME/.pub-cache/bin" >> $GITHUB_ENV

    - name: Setup global packages
      shell: bash
      run: |
        dart pub global activate melos
        dart pub global activate fvm
        dart pub global activate flutterfire_cli 0.3.0-dev.16 --overwrite

    - name: Precache
      shell: bash
      run: |
        fvm flutter --version
        fvm flutter precache
