name: Setup Flutter
description: Setup Flutter SDK

inputs:
  use_local_dart:
    description: Use local Dart SDK
    required: true
    default: "false"

  flutter_branch:
    description: Flutter branch
    required: false
    default: "beta"

runs:
  using: "composite"
  steps:
    - name: Cache Flutter
      if: inputs.use_local_dart == 'false'
      uses: actions/cache@v3.3.1
      with:
        path: ~/fvm/versions
        key: flutter-v1

    - name: Clone Flutter
      if: inputs.use_local_dart == 'false'
      shell: bash
      run: |
        git clone https://github.com/flutter/flutter.git \
          -b ${{ inputs.flutter_branch }} \
          ~/fvm/versions/${{ inputs.flutter_branch }}

    - run: which dart
      shell: bash

    - name: PATH
      if: inputs.use_local_dart == 'false'
      shell: bash
      run: |
        echo "~/fvm/versions/${{ inputs.flutter_branch }}/bin" >> $GITHUB_PATH
        echo "~/.pub-cache/bin" >> $GITHUB_PATH

    - name: Setup global packages
      shell: bash
      run: |
        which dart
        dart --version
        dart pub global activate melos
        dart pub global activate fvm
        dart pub global activate flutterfire_cli 0.3.0-dev.16 --overwrite

    - name: Dart Version
      shell: bash
      run: |
        which dart
        dart --version

    - name: Flutter Version
      if: always()
      shell: bash
      run: |
        which flutter
        flutter --version

    - name: Precache
      shell: bash
      run: |
        flutter precache
