// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEX-cwQ94PlQJR-PvnAcIm2ooO0TV3LCc',
    appId: '1:301249130862:android:43d09df27f5e1b5f0b917f',
    messagingSenderId: '301249130862',
    projectId: 'ubiscope',
    storageBucket: 'ubiscope.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3X_fAGCC1EYfKExPzvLwWwO_XkMvxpkA',
    appId: '1:301249130862:ios:4c57371890d706ce0b917f',
    messagingSenderId: '301249130862',
    projectId: 'ubiscope',
    storageBucket: 'ubiscope.appspot.com',
    androidClientId: '301249130862-6k3blhia0eskbv6kk7tccf3qukjqj1ek.apps.googleusercontent.com',
    iosClientId: '301249130862-ec5ir90repes7obtghgnld1ombo1l1vp.apps.googleusercontent.com',
    iosBundleId: 'dev.kingu.ubiscope.app',
  );
}
