// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK9fvWmFeQWM3X1w2i2HP6ss0GY4fnsh0',
    appId: '1:636244043019:android:0e72937faed00efaf5ee0e',
    messagingSenderId: '636244043019',
    projectId: 'ubiscope-dev',
    storageBucket: 'ubiscope-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt5_9MB30dJPkTPzGYw1kYVLs_hoeoZac',
    appId: '1:636244043019:ios:b3dbac9fec3b6c5ef5ee0e',
    messagingSenderId: '636244043019',
    projectId: 'ubiscope-dev',
    storageBucket: 'ubiscope-dev.appspot.com',
    androidClientId: '636244043019-be00rki79l1nug0iamjbt4v8pmiu54vi.apps.googleusercontent.com',
    iosClientId: '636244043019-6r22av360bj4sgeen1vp8eustu01b96l.apps.googleusercontent.com',
    iosBundleId: 'dev.kingu.ubiscope.app.dev',
  );
}
