name: Closed Pull Requests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *" # JTS 04:00

env:
  FLUTTER_VERSION: "beta" # FIXME

jobs:
  build:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: # FIXME
          - ubuntu-latest
          - self-hosted
        flavor: # FIXME
          - dev
          - prod
        package: # FIXME
          - client_app

    runs-on: ${{ matrix.os }}

    steps:
      ### Setup ###
      - uses: actions/checkout@v3

      - name: Gradle Cache
        if: matrix.os == 'ubuntu-latest'
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ matrix.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-v1

      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: ${{ env.FLUTTER_VERSION }}
          cache: ${{ matrix.os != 'self-hosted' }}
          cache-key: "flutter-:channel:-:version:"

      - name: Flutter Setup
        run: |
          flutter --version
          dart pub global activate melos
          dart pub global activate fvm
          dart pub global activate flutterfire_cli 0.3.0-dev.16 --overwrite

          fvm install ${{ env.FLUTTER_VERSION}}

      ### Decode ###
      - name: Decode signingConfigs.gradle
        if: matrix.os == 'ubuntu-latest'
        working-directory: packages/${{ matrix.package }}
        run: |
          echo ${{ secrets.SIGNING_CONFIGS_CLIENT_APP_BASE64 }} | base64 --decode > android/app/signingConfigs.gradle

      - name: Decode upload-keystore.jks
        if: matrix.os == 'ubuntu-latest'
        working-directory: packages/${{ matrix.package }}
        run: |
          echo ${{ secrets.UPLOAD_KEYSTORE_CLIENT_APP_BASE64 }} | base64 --decode > android/app/upload-keystore.jks

      ### Build ###
      - name: Build Android Dev
        if: matrix.os == 'ubuntu-latest' && matrix.flavor == 'dev'
        run: melos run build:apk:dev --no-select

      - name: Build Android Prod
        if: matrix.os == 'ubuntu-latest' && matrix.flavor == 'prod'
        run: melos run build:appbundle:prod --no-select

      - name: Build iOS Dev
        if: matrix.os == 'self-hosted' && matrix.flavor == 'dev'
        run: melos run build:ios:no-codesign:dev --no-select

      - name: Build iOS Prod
        if: matrix.os == 'self-hosted' && matrix.flavor == 'prod'
        run: melos run build:ios:no-codesign:prod --no-select
