name: Firebase Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: "Choose environment to deploy"
        options:
          - dev
          - prod
        required: true
        default: dev
      package:
        type: choice
        description: "Choose package to deploy"
        options: # FIXME
          - client_app
        required: true

run-name: Firebase Deploy ${{ inputs.package }} ${{ inputs.env }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs.package }}-${{ github.event.inputs.env }}
  cancel-in-progress: true

jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      ### Setup ###
      - uses: actions/checkout@v4

      - name: Setup Firebase CLI Dev
        uses: ./.github/actions/setup-firebase-cli
        if: inputs.env == 'dev'
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER_DEV }}
          service_account: ${{ vars.SERVICE_ACCOUNT_DEV }}

      - name: Setup Firebase CLI Prod
        uses: ./.github/actions/setup-firebase-cli
        if: inputs.env == 'prod'
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER_PROD }}
          service_account: ${{ vars.SERVICE_ACCOUNT_PROD }}

      ### Deploy ###
      - name: Deploy Dev
        if: inputs.env != 'prod'
        working-directory: packages/${{ inputs.package }}
        run: |
          firebase use dev --debug
          firebase deploy --force

      - name: Deploy Prod
        if: inputs.env == 'prod'
        working-directory: packages/${{ inputs.package }}
        run: |
          firebase use prod --debug
          firebase deploy --force
