name: Precache Flutter

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *" # JTS 03:00

jobs:
  precache:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-flutter
