name: Precache Flutter

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *" # JTS 03:00

jobs:
  precache:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-flutter

      - run: which flutter
      - run: flutter --version

      - run: which dart
      - run: dart --version

      - run: which fvm
      - run: fvm flutter --version
