name: Pull Requests Firebase

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "packages/*/firebase/**"
      - "packages/*/firebase.json"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        package: # FIXME
          - client_app
        flavor: # FIXME
          - dev
          - prod
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      ### Set up ###
      - uses: actions/checkout@v4

      - name: Setup Firebase CLI Dev
        uses: ./.github/actions/setup-firebase-cli
        if: matrix.flavor == 'dev'
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER_DEV }}
          service_account: ${{ vars.SERVICE_ACCOUNT_DEV }}

      - name: Setup Firebase CLI Prod
        uses: ./.github/actions/setup-firebase-cli
        if: matrix.flavor == 'prod'
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER_PROD }}
          service_account: ${{ vars.SERVICE_ACCOUNT_PROD }}

      ### Test ###
      - name: Test
        working-directory: packages/${{ matrix.package }}
        run: |
          ./firebase_emulators_test.sh ${{ matrix.flavor }}

  pull_request_conclusion:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Pull request conclusion"
