name: Pull Requests

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - ".github/**"
      - "packages/*/ios/**"
      - "packages/*/android/**"
      - "packages/*/firebase/**"
      - "packages/*/firebase.json"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      ### Set up ###
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-flutter
        with:
          use_local_dart: false

      ### Analyze ###
      - name: Analyze
        run: |
          melos run analyze --no-select
          git diff --exit-code

  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      ### Set up ###
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-flutter

      ### Test ###
      - name: Test
        run: |
          melos run flutter:test --no-select
