name: Pull Requests for iOS

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "packages/*/ios/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 30
    runs-on: macos-13
    steps:
      ### Set up ###
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-flutter

      - name: Pods Cache
        uses: actions/cache@v3
        with:
          path: |
            packages/client_app/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      ### Build ###
      - run: melos run build:ios:config-only
      - run: git diff --exit-code
      - run: melos run build:ios:no-codesign:dev --no-select

  pull_request_conclusion:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Pull request conclusion"
