name: Pull Requests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "packages/*/lib/**"
      - "packages/*/ios/**"
      - "packages/*/android/**"
      - "packages/*/test/**"
      - "packages/*/assets/**"
      - "packages/*/pubspec.*"
      - ".github/workflows/pull_requests.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      ### Set up ###
      - uses: actions/checkout@v3

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.5.0
        with:
          sdk: beta

      - name: Flutter Setup
        run: |
          dart pub global activate melos
          dart pub global activate fvm

          fvm install

      - name: Analyze
        run: |
          melos run analyze --no-select

      ### Test ###
      - name: Test
        run: |
          melos run flutter:test --no-select
