name: Pull Requests for Android

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "packages/*/android/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      ### Set up ###
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-flutter
        with:
          use_local_dart: false

      - uses: ./.github/actions/setup-android-signing
        with:
          package: client_app
          signing_configs_base64: ${{ secrets.SIGNING_CONFIGS_CLIENT_APP_BASE64 }}
          upload_keystore_base64: ${{ secrets.UPLOAD_KEYSTORE_CLIENT_APP_BASE64 }}

      ### Build ###
      - name: build
        run: melos run build:apk:dev --no-select

  pull_request_conclusion:
    needs:
      - build
    runs-on: ubuntu-latest
